name: list updated files
run-name: list diff files
on: [pull_request]

jobs:
  list-diff:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_BASE_REF $GITHUB_REF
      - run: git diff $GITHUB_BASE_REF --name-only