name: list updated files
run-name: list diff files
on: [pull_request]

jobs:
  list-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "${{ github.base_ref }} ${{ github.ref }}"
      - run: git diff origin/${{ github.base_ref }} --name-only