on: [push]

jobs:
  diff-action-test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: diff notebooks
        uses: ./ # Uses an action in the root directory
        id: diff
        with:
          remote: origin/diff-notebooks
